version: '3.5'
services:
  postgresql:
    image: postgres:12-alpine
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: <adminusername>
      POSTGRES_PASSWORD: <adminuserpassword>
      POSTGRES_HOST_AUTH_METHOD: password
    container_name: <container-name>
    restart: always
    volumes:
     - ./config/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
     - ./orderhistory_postgresql_data:/var/lib/postgresql/data
